### ISSUE TITLE
是否可以支持下裁剪图片的时候增加一个圆形裁剪

### ISSUE THREAD

**Issue by anzhuojinjie** [yanzhenjie/Durban#1]
是否可以支持下裁剪图片的时候增加一个圆形裁剪，或者是自己改的需要怎么改

**Comment by yanzhenjie** [comment]
我不打算在Durban中加圆形裁剪，理由如下：
1. 比如100 * 100的图，裁剪成原形是可以的，但是裁剪成圆形后就不能显示为100 * 100的方形了。
2. 一般我们使用`CircleImageView`类似的View来显示原型图，这样不会损坏原来的图片。
